[package]
name = "smbserver"
version = "0.1.0"
edition = "2024"

[dependencies]
binrw = "0.14"
tokio = { version = "1.48", features = ["io-util", "rt"] }

[dev-dependencies]
smb = { version = "0.11", default-features = false, features = ["async", "sign", "encrypt"] }
smb-fscc = "0.11"
smb-transport = { version = "0.11", default-features = false, features = ["async"] }
futures-core = "0.3"
futures-util = "0.3"
tokio = { version = "1.48", features = ["full", "test-util"] }
ntest = "0.9"
sspi = { version = "=0.18.7", default-features = false, features = ["ring"] }
